### ISSUE TITLE
dependency on func.yaml for git on-cluster builds

### ISSUE THREAD

**Issue by Shashankft9** [knative/func#1446]
Currently, when `--remote` and `--git-url` are used for on git cluster build, `func deploy` has a hard dependency on `func.yaml`.
I think I should be able to run it from anywhere, since all the code is present on a git project. The behavior shouldn't change for non VCS on cluster builds. 

/kind enhancement

**Comment by lkingland** [comment]
Yes, this is correct.  I seem to remember this issue being mentioned elsewhere already, but a quick search through issues provided nothing.

In short, when running a --remote build along with --git-url, one should not need the function source locally.  It is triggering a remote build with all context expected to be in the source code of that url.

**Comment by lkingland** [comment]
That's unfortunate.  This is of course a longer discussion, but since `func deploy --remote --git-url=[source]` is conceptually doing one thing:  telling another network-available process to run `git pull [source] && func deploy`, this _should_ be possible with a little work.  Maybe not a good-first-issue, however.

As a workaround, we could of course pull the source code into a temp directory locally and then `func deploy --remote --path=...`

**Comment by lance** [comment]
While working on a fix I considered adding `--name` to the `func deploy` command - valid only with the `--git-url` flag. But I'm not sure how much I like this either.

**Comment by lkingland** [comment]
Maybe not related but.... when initializing a git repository (`git init`),  a name is not required.  This is of course because a git repository is what it is, regardless of name.  In perhaps the same vein, the only time a name is _really_ required, is when deploying (in order to determine the desired DNS name/route).  So perhaps this is a signal that having <name> be optional on create, but required on deploy, is correct-ish.
