### ISSUE TITLE
Question: Ignoring files with kn func build

### ISSUE THREAD

**Issue by pipoe2h** [knative/func#1450]
Hi,

I've been trying to find some documentation about how to ignore files when running `kn func build`, but so far I'm failing to find something. Is it possible to ignore files when running `kn func build`?

When I use the command `kn func create -l python function_name`, this creates a structure that includes a `.gitignore` file that includes with a default value to ignore `/.func`. Then, when I run the command `kn func build`, the directory `.func` gets copied into the container image. The file `.gitignore` seems to apply only for when pushing the code to git, but not when building the images. 

Thanks in advance!

**Comment by lkingland** [comment]
This is a known issue, and is a good enhancement request.  We were hoping to have a `.funcignore` file which would work much like `.gitignore` but for func-related tasks such as build (and especially `--remote` builds as this could be quite long if the local directory contains a large amount of files!)

**Comment by pipoe2h** [comment]
Thanks for the info. Is there any workaround/process/way to work that you can think in the interim?

Right now I'm copying the code to a new folder and executing the build from there because more than once I've forgotten that this is copying the entire workspace that includes .env, all the __pycache__, and so on. 

Thanks again and keep the good work.

**Comment by lkingland** [comment]
Thanks for helping us test the system, and assign priority to issues like this.

Your workaround seems like a good one to me.  The fastest way to get this done is to just implement the feature.  Below are some quick notes on how this should probably be implemented:

Each of the two builder implementations, Pack and S2I, will need to be updated to respect a .funcignore file if it is present.  This file should be of .gitignore format, and perhaps use `github.com/sabhiram/go-gitignore` since this library is already being used by the Pack builder internally.  This library has a `ComileIgnoreFile([path])` function which returns the .funcignore as a structure with a slice of `IgnorePattern`s, each of which has an actual `regexp.Regex` as its `.Pattern` member; making the next two steps straightforward:

In the Pack builder implementation, located in `buildpacks/builder.go`, each of the lines of the .funcignore will need to be added to the [pack builder's configuration](https://github.com/knative/func/blob/main/buildpacks/builder.go#L110) as an exclude`pack.BuildOptions.ProjectDescriptor.Build.Excludes`

In the S2I builder implementation, located in `s2i/builder.go`, each of the lines of the .funcignore will need to be concatenated into a single large regex and set on the S2I builder's configuration as the single exclude regex `api.Config.ExcludeRegExp`

These each should  have a test which uses a mock implementation for the builder to confirm that the .funcignore file was
correctly read and parsed into the expected string (no need to actually test if the files are excluded from the build, as this is the responsibility and an implementation detail of their requisite libraries).  Ideally there would be a test confirming invalid .funcignore files properly fail fast as well.

I will get to implementing this as soon as possible, but will mark this as a good first issue; should anyone else feel like jumping in.
