### ISSUE TITLE
How to use func in air gapped environment?

### ISSUE THREAD

**Issue by ashum81** [knative/func#1452]
I have local mirrors of docker.io and gcr.io registries. How to use them for building functions with func?

I try to deploy with a command:

`func deploy --registry docker-local.registry.mydomain.org/test --builder-image gcr-docker-local.registry.mydomain.org/paketo-buildpacks/builder:base`

🕗 Still building

2022/12/02 11:19:21.368501 DEBUG:  Pulling image gcr-docker-local.registry.mydomain.org/paketo-buildpacks/builder:base
base: Pulling from paketo-buildpacks/builder
Digest: sha256:00a312804f92da4b0633ae727ca36e8e58dcaacf2217d15ea22ba70d1d0d6f95
Status: Image is up to date for gcr-docker-local.registry.mydomain.org/paketo-buildpacks/builder:base
2022/12/02 11:19:21.752679 DEBUG:  Selected run image index.docker.io/paketobuildpacks/run:base-cnb
2022/12/02 11:19:21.752684 DEBUG:  Pulling image index.docker.io/paketobuildpacks/run:base-cnb

Error: failed to build the function: invalid run-image 'index.docker.io/paketobuildpacks/run:base-cnb': Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by jrangelramos** [comment]
Hi @ashum81 which cluster/kubernetes environment are you using / targeting to?

**Comment by jrangelramos** [comment]
Hi @ashum81, as far as I know running a func build in a air-gapped environment using the default pack builders and Docker engine might be challenging. That's because the buildpack itself contains additional dependencies such as a runner image and resources (runtime tarballs), that also should be mirrored or proxy'ed as well.

For example in additional to the `gcr.io/paketo-buildpacks/builder:base` image, you would need to mirror also the runner image, in this case, `gcr.io/paketo-buildpacks/run:base-cnb` on you local registry.
But to make it possible to resolve mirroring should (probably) be done directly on the container engine, so that you internal dependencies (like the `run:base-cnb`) image should be resolved by the container.

On Docker you would probably need to configure docker daemon registry-mirror option on dockerd service or `/etc/docker/daemon.json`:

```
  "registry-mirrors": ["https://gcr-docker-local.registry.mydomain.org"]
```

Alternativellty, when using Podman as container engine, you could configure by changeing `/etc/containers/registries.conf` as below.
```
[[registry]]
 prefix = "gcr.io/paketo-buildpacks"
 [[registry.mirror]]
 location = "gcr-docker-local.registry.mydomain.org/paketo-buildpacks"
```

By going thru this path, you don't need to specify the builer image on `func build|deploy` so that the paketo image and its dependencies would be resolved by the container engine itself.
However, paketo also pulls additional resources from internet.Just taking a NodeJS build as example, it pulls a node runtime from https://deps.paketo.io/node/node_v18.12.1_linux_x64_bionic_58cddcd4.tgz) so you would need to cache it and make it locally accessible on your network (let's say using a reverse proxy w/ nginx or apache), otherwise the buildpack wouldn't be able to pull it.

For SpringBoot or Quarkus function, additional to these concerns you would need to care about the Maven dependencies. They you would need to be cached in a local repo (i.e. Nexus or JFrog) and have it properly mapped on your `settings.xml` or `pom.xml`.

Hope it give you some directions.
