### ISSUE TITLE
Dapr annotations always set

### ISSUE THREAD

**Issue by matzew** [knative/func#1566]
The `dapr.io` annotations are now always set, on the `KSVC` metadata:
https://github.com/knative/func/blob/main/pkg/knative/deployer.go#L394-L398

While these have no effect, it does feel a bit verbose that they are always there, given that the majority of KSVC might not use Dapr at all. It would be good if this could be enabled only with a flag or so

**Comment by lkingland** [comment]
This is not the long-term solution, but is rather the simplest path to accomplish the goal at our current level of maturity/complexity.

The goal is that Functions integrate with runtime services like Dapr by default if it is installed into the cluster, without requiring explicit configuration, a rebuild, a redeploy or any action on the part of a Function developer outside of their code itself.  It should "just work".

This is how Dapr expects services to identify their integration contract.  So while I agree with you that it seems verbose, this is apparently the simplest way to accomplish the zeroconf goal at our current level of complexity.  It is not, however, the ideal long-term solution, as we may need to add many more annotations for other runtimes:

Longer-term solution 1:  the Functions In-Cluster Agent

A Functions operator/agent within the cluster which is more intelligent:  for example detecting Dapr was/is installed and then applying the labels to all deployed functions.

Longer-term soution 2:  The Runtime Functions API

Much like the runtime Dapr API, we have discussed providing a locally-available HTTP REST API to Functions.  This would be a superset of Dapr and other runtime services which we natively support (if installed in the cluster).  This listener could itself trigger the annotations lazily.

Longer-term solution 3: Code Metaanalysis

As part of our effort to maintain dependency inversion in function source code, we need to keep direct dependencies on the underlying functions infrastructure out of the function itself.  In order to provide more advanced features beyond the simple functions of today (examples outside the scope of this issue), it will require some level of code analysis on `func deploy`.  As part of this scan, we could add a detector for 'dapr' (and other supported runtime APIs), adding the labels only as necessary.


Any other solutions which preserve "it just works" from the perspective of the function developer I would love to hear; extra annotations on every function instance irks me as well.  But I would gently suggest/vote that we avoid flags like `export FUNC_ENABLE_DAPR=true` for anything except for experimental features, and instead choose this simple solution for now at least.

**Comment by lkingland** [comment]
After the weekend with some time to reflect, I have become less sure of my position above:

The annotations aren't too much of a bother if they enable zero-config Dapr support for a developer, but I don't think injecting the Dapr sidecar by default to all Functions, regardless of their usage of the Dapr runtime, is as clear of an answer.

I will bring this up in this week's call, to see if adding a configuration setting to opt-in to Dapr on a per-function basis makes sense to others as well.
