### ISSUE TITLE
API in Integrator's Guide outdated

### ISSUE THREAD

**Issue by chickenlj** [knative/func#1751]
https://github.com/knative/func/blob/main/docs/integrators_guide.md

For example, client.Create func has been removed, which method should I use instead.

```go
if err := client.Create(funcTest); err != nil {
		log.Fatal(err)
	}
```

```go
pusher, err := docker.NewPusher()
	if err != nil {
		log.Fatal(err)
	}
	deployer, err := knative.NewDeployer("")
	if err != nil {
		log.Fatal(err)
	}
```

**Comment by chickenlj** [comment]
I think it's `client.New(funcTest)`, right?

**Comment by lkingland** [comment]
Yes this issue is correct, this document will be updated soon, as we are beginning a larger documentation-update push for the next version.  Thank you for pointing out that this document needs to be updated as well.

For an always-correct document which showcases how to use the client library, take a look at the test suite in `client_test.go`, which works from simple to advanced from top to bottom.

In this case yes, the correct way to instantiate a client is with a simple `New()`.  This will result in a new client with most of its implementations mocked.   You can pass it a builder, pusher, and deployer as needed.  The `cli` package has an example of using all permutations.
