### ISSUE TITLE
Document all values/defaults in func.yaml

### ISSUE THREAD

**Issue by mvinkler** [knative/func#1841]
There should be a section for each runtime which documents all possible configuration options and used defaults. 

Without this, user cannot easily find out what defaults are applied to their application (for example definition of health checks for a Quarkus runtime).

**Comment by lance** [comment]
We do currently have a document for `func.yaml` but it clearly is missing some references such as the health endpoints. https://github.com/knative/func/blob/main/docs/reference/func_yaml.md

**Comment by lkingland** [comment]
Many systems solve this conundrum by writing a fully-populated, but commented-out config file to disk, which has all (commented) values set to their defaults at time of installation.

We can of course not do this exactly in this manner due to the choice of yaml as our config file format.  However, we could potentially get most of the benefit by instead prepending this fully-populated config as a header to func.yaml on save.

The comments would not inhibit the parsing of the config, and we would be free to add as much exposition as is necessary, while [not falling into the pitfalls of a pre-populated config](https://github.com/knative/func/issues/1839#issuecomment-1618225141).

**Comment by lkingland** [comment]
We can also write the `func.yaml` as a Go template, as is outlined in #1853
