### ISSUE TITLE
func "Incorrect credentials, please try again." against index.docker.io

### ISSUE THREAD

**Issue by BLuchterhand** [knative/func#2542]
I am unable to validate my docker credentials through `kf func deploy`, recieving `Incorrect credentials, please try again.`
This is `func version v0.42.1`, and it's attempting to validate against the `index.docker.io` registry:

```
hello kn func deploy --registry docker.io/<my registry>/go-functions
function up-to-date. Force rebuild with --build
Please provide credentials for image registry (index.docker.io).
? Username: **********
? Password: **********
Incorrect credentials, please try again.
```

However, I can login to docker just fine with my credentials. Testing with both my email and my username, I've successfully logged in via:

- Existing password through UI
- Existing password through login in CLI (`docker login`)
- Existing token through CLI
- Newly generated token through CLI
- Newly changed password through UI
- Newly changed password through CLI

Explicitly, logging in with `docker login index.docker.io` and my same credentials works just fine.

I tried setting my credentials in 
`~/.docker/config.json` 

with no luck, and similarly setting the env variables:
```
export DOCKER_REGISTRY_SERVER=index.docker.io
export DOCKER_USER=<your-docker-username>
export DOCKER_PASSWORD=<your-docker-password-or-token>
```

But no luck here... Is there something obvious I am missing? To me it seems like the `func deploy` is ignoring my docker credentials, variables, and is similarly somehow mishandling the data I enter in manually. 

Edit: For full disclosure - this is for a personal project and I have very little kubernetes experience. Just testing Knative for a serverless project, though I wouldn't expect to need much more Kubernetes experience to get this to work... any help is greatly appreciated.

**Comment by gauron99** [comment]
Hi @BLuchterhand, Im guessing the `docker.io/<my registry>/go-functions` is an image, you can use `--image` flag for that, instead of registry as `--image docker.io/<my registry>/go-functions` OR alternatively you can remove `/go-functions` and keep only the "registry" part as `--registry docker.io/<my registry>`

Sorry about the error its not very informative. Im currently working on fixing that

**Comment by darylangg** [comment]
I ran into the same issue, but found success by using 
`func build -b=s2i --image=docker.io/<username>/app:latest`
`func deploy -b=s2i --image=docker.io/<username>/app:latest`

**Comment by gauron99** [comment]
@darylangg what did you try to run that failed? deploy with `--registry`? or with `--image` flag?

**Comment by darylangg** [comment]
I initially tried with 
`func deploy -b=s2i --registry=docker.io/<username>`, but kept running into the invalid credentials error. 

Similar to @BLuchterhand, I was able to login with docker login and also tried generating a docker hub PAT but it didn't work.

**Comment by gauron99** [comment]
@darylangg Hi
im unable to reproduce the issue using your scenario using either builder and being logged in/out of docker prior to running these commands. It is strange that running `build` prior to `deploy` resolved the issue because it uses `build` underneath when an image is 'to be built'. 
Some ideas that mightve happened there is that there were wrong credentials saved beforehand or perhaps an old image of different name (or registry) in the config, therefore running `build` forced the update.

Either way, Im glad you were able to resolve your issue at last!

**Comment by labidiaymen** [comment]
I have the same error : 
func deploy 
function up-to-date. Force rebuild with --build
Please provide credentials for image registry (index.docker.io).
? Username: *******
? Password: ********************
Incorrect credentials, please try again.

**Comment by ngtw-j** [comment]
if its already built, you can try deploying with --build=false
