### ISSUE TITLE
On-cluster build: Use unique PVC name used by a Pipeline

### ISSUE THREAD

**Issue by lance** [knative/func#850]
[UPDATE] by @zroubalik :
Reasoning behind this: if for some reasons the PVC created for a function is not ready/healthy and we would like to re-create the function (or one with the same name) we won't be able to do so, because the Pipeline will fail on the PVC creation. 

We can just append a random number to the PVC name, but we need to be sure that we are using the correct PVC for the function -> we need to track the generated name somewhere locally or maybe use a k8s labels to find out whether the PV for this function already exists.

**Comment by grafvonb** [comment]
@zroubalik what about other ideas like `func deploy --remote --force` or `func deploy --remote --reset` where it can mimic the behavior of `func delete` (or part of it)? In my opinion we should avoid "producing" too many temporary resources that need to be cleaned up later because they cause e.g. high storage consumption, e.g. the default size of a pvc on AWS with the EBS volume type is 1Gi and cannot be changed even if our default size is 256Mi.
