### ISSUE TITLE
Global configuration for functions

### ISSUE THREAD

**Issue by lance** [knative/func#901]
Allow the user to set global configuration options, for example the image registry, with `func config --global`.

**Comment by nainaz** [comment]
**Context**: Enterprises and developers using the same configuration parameters that may be different from the default ones for creating functions currently has to change the values repeatedly. Cluster admin would like to set up the common and standard parameters for the developers

**Story**:

As Dina the developer,

I should be able set some global configuration parameters across my machine/cluster

so that I can have the same configuration override applied to all my functions and not fiddle with the default ones provided every time.




As cluster admin,

I should be able set some global configuration parameters across my machine/cluster

so that I can have the developers user the consistent approved configuration values override applied to all functions created in the org 

**Acceptance Criteria**
GIVEN that I provide the global override of configuration parameter 

WHEN I write and create my functions

THEN globally set configurations should be used rather than the default ones while building and deploying my function.
